version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: integration_aws_test
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=dynamodb, sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/dat
    volumes:
      - "./.localstack:/var/lib/localstack"